# Site settings
title: Laurent Pellegrino
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pellegrino.link" # the base hostname & protocol for your site

github_username:  lpellegr
twitter_username: lpellegr

# Build settings
markdown: kramdown
sass:
  style: :compressed
  
